{"name": "Проверка: при попытке создать пользователя, идентичного уже существующему, вернётся ошибка 403", "status": "passed", "start": 1712228544233, "stop": 1712228544667, "uuid": "27d8ddee-722a-4c31-b600-04ebc4f562ee", "historyId": "38da67a6a1af93251ba48d51d6dc983a", "testCaseId": "38da67a6a1af93251ba48d51d6dc983a", "fullName": "tests.test_create_new_user.TestCreateNewUser#test_create_two_same_users_causes_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_new_user"}, {"name": "subSuite", "value": "TestCreateNewUser"}, {"name": "host", "value": "Olyas-MacBook-Air.local"}, {"name": "thread", "value": "48728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_new_user"}]}