{"name": "Проверка: при попытке получить заказы без авторизации вернётся ошибка 401", "status": "passed", "start": 1712228553551, "stop": 1712228553722, "uuid": "cc7f5bd6-ad03-476f-990b-f9d94ffec2a9", "historyId": "0d32124ac6c020ebb7c183e6b9337c24", "testCaseId": "0d32124ac6c020ebb7c183e6b9337c24", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_unauthorized_user_orders_causes_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "Olyas-MacBook-Air.local"}, {"name": "thread", "value": "48728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}